--
--テーブル削除用SQL
--
--DROP TABLE JSSSYSTEM.MST_USER CASCADE CONSTRAINTS;
--DROP TABLE JSSSYSTEM.MST_CATEGORY CASCADE CONSTRAINTS;
--DROP TABLE JSSSYSTEM.MST_QUESTION_IMG CASCADE CONSTRAINTS;
--DROP TABLE JSSSYSTEM.MST_KAISETSU_IMG CASCADE CONSTRAINTS;
--DROP TABLE JSSSYSTEM.MST_ANSWER CASCADE CONSTRAINTS;
--DROP TABLE JSSSYSTEM.MST_QUESTION CASCADE CONSTRAINTS;
--DROP TABLE JSSSYSTEM.TRN_ANSWER_HISTORY CASCADE CONSTRAINTS;
--
--ユーザマスタ
--
CREATE TABLE "JSSSYSTEM"."MST_USER" ( 
  "USER_ID" VARCHAR2(10) NOT NULL
  , "USER_NAME" VARCHAR2(20) NOT NULL
  , "PASSWORD" VARCHAR (20) NOT NULL
  , "LOGIN_DATE" DATE NOT NULL
  , "TEACHER_FLG" VARCHAR2(1) DEFAULT '0' NOT NULL
); 
ALTER TABLE JSSSYSTEM.MST_USER ADD CONSTRAINT PK_MST_USER PRIMARY KEY (USER_ID); 
--
--分類マスタ
--
CREATE TABLE "JSSSYSTEM"."MST_CATEGORY" ( 
  "CATEGORY_ID" VARCHAR2(10) NOT NULL
  , "SUBJECT" NVARCHAR2(50) NOT NULL
  , "CATEGORY" NVARCHAR2(50) NOT NULL
); 
ALTER TABLE JSSSYSTEM.MST_CATEGORY ADD CONSTRAINT PK_MST_CATEGORY PRIMARY KEY (CATEGORY_ID); 
--
--解答マスタ
--
CREATE TABLE "JSSSYSTEM"."MST_ANSWER" ( 
  "ANSWER_ID" VARCHAR2(20) NOT NULL
  , "ANSWER" VARCHAR2(1) NOT NULL
  , "KAISETSU" NVARCHAR2(900)
  , "ANSWER_TABLE_SQL" VARCHAR2(100)
  , "INS_DATE" DATE
  , "INS_USER" VARCHAR (20)
  , "UPD_DATE" DATE
  , "UPD_USER" VARCHAR (20)
);
ALTER TABLE JSSSYSTEM.MST_ANSWER ADD CONSTRAINT PK_MST_ANSWER PRIMARY KEY (ANSWER_ID);
--
--問題マスタ
--
CREATE TABLE "JSSSYSTEM"."MST_QUESTION" ( 
  "QUESTION_ID" VARCHAR2(20) NOT NULL
  , "CATEGORY_ID" VARCHAR2(10) REFERENCES MST_CATEGORY(CATEGORY_ID) NOT NULL
  , "ANSWER_ID" VARCHAR2(20) REFERENCES MST_ANSWER(ANSWER_ID) NOT NULL
  , "SENTAKU_A" NVARCHAR2(200) NOT NULL
  , "SENTAKU_B" NVARCHAR2(200) NOT NULL
  , "SENTAKU_C" NVARCHAR2(200) NOT NULL
  , "SENTAKU_D" NVARCHAR2(200) NOT NULL
  , "QUESTION" NVARCHAR2(900) NOT NULL
  , "QUESTION_TITLE" NVARCHAR2(100) NOT NULL
  , "DEL_FLG" VARCHAR2(1) DEFAULT '0'
  , "INS_DATE" DATE
  , "INS_USER" VARCHAR (20)
  , "UPD_DATE" DATE
  , "UPD_USER" VARCHAR (20)
); 
ALTER TABLE JSSSYSTEM.MST_QUESTION ADD CONSTRAINT PK_MST_QUESTION PRIMARY KEY (QUESTION_ID);
--
--解答履歴テーブル
--
CREATE TABLE "JSSSYSTEM"."TRN_ANSWER_HISTORY" ( 
  "ANSWER_HISTORY_ID" VARCHAR2(20) NOT NULL
  , "USER_ID" VARCHAR2(10) REFERENCES MST_USER(USER_ID) NOT NULL
  , "QUESTION_ID" VARCHAR2(20) REFERENCES MST_QUESTION(QUESTION_ID)
  , "USER_ANSWER" VARCHAR2(1)
  , "ANSWER_DATE" DATE
); 
ALTER TABLE JSSSYSTEM.TRN_ANSWER_HISTORY ADD CONSTRAINT PK_TRN_ANSWER_HISTORY PRIMARY KEY (ANSWER_HISTORY_ID);
--
--問題画像テーブル
--
CREATE TABLE "JSSSYSTEM"."MST_QUESTION_IMG" ( 
  "QUESTION_ID" VARCHAR2(20) NOT NULL REFERENCES MST_QUESTION(QUESTION_ID)
  , "IMG_PATH" VARCHAR2(100) NOT NULL
); 
ALTER TABLE JSSSYSTEM.MST_QUESTION_IMG ADD CONSTRAINT PK_QUESTION_ID PRIMARY KEY (QUESTION_ID);
--
--解説画像テーブル
--
CREATE TABLE "JSSSYSTEM"."MST_KAISETSU_IMG" ( 
  "ANSWER_ID" VARCHAR2(20) NOT NULL
  , "IMG_PATH" VARCHAR2(100) NOT NULL
); 
ALTER TABLE JSSSYSTEM.MST_KAISETSU_IMG ADD CONSTRAINT PK_ANSWER_ID PRIMARY KEY (ANSWER_ID); 